export interface AllahName {
  id: number;
  arabic: string;
  transliteration: string;
  meaning: string;
}

export const ALLAH_NAMES: AllahName[] = [
  { id: 1, arabic: "ٱلرَّحْمَـٰنُ", transliteration: "Ar-Rahman", meaning: "The Entirely Merciful" },
  { id: 2, arabic: "ٱلرَّحِيمُ", transliteration: "Ar-Rahim", meaning: "The Especially Merciful" },
  { id: 3, arabic: "ٱلْمَلِكُ", transliteration: "Al-Malik", meaning: "The King and Owner of Dominion" },
  { id: 4, arabic: "ٱلْقُدُّوسُ", transliteration: "Al-Quddus", meaning: "The Most Holy" },
  { id: 5, arabic: "ٱلسَّلَامُ", transliteration: "As-Salam", meaning: "The Source of Peace" },
  { id: 6, arabic: "ٱلْمُؤْمِنُ", transliteration: "Al-Mu'min", meaning: "The Giver of Faith and Security" },
  { id: 7, arabic: "ٱلْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meaning: "The Guardian and Overseer" },
  { id: 8, arabic: "ٱلْعَزِيزُ", transliteration: "Al-Aziz", meaning: "The Almighty" },
  { id: 9, arabic: "ٱلْجَبَّارُ", transliteration: "Al-Jabbar", meaning: "The Compeller and Restorer" },
  { id: 10, arabic: "ٱلْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaning: "The Supreme" },
  { id: 11, arabic: "ٱلْخَالِقُ", transliteration: "Al-Khaliq", meaning: "The Creator" },
  { id: 12, arabic: "ٱلْبَارِئُ", transliteration: "Al-Bari", meaning: "The Originator" },
  { id: 13, arabic: "ٱلْمُصَوِّرُ", transliteration: "Al-Musawwir", meaning: "The Fashioner" },
  { id: 14, arabic: "ٱلْغَفَّارُ", transliteration: "Al-Ghaffar", meaning: "The Constant Forgiver" },
  { id: 15, arabic: "ٱلْقَهَّارُ", transliteration: "Al-Qahhar", meaning: "The All-Subduer" },
  { id: 16, arabic: "ٱلْوَهَّابُ", transliteration: "Al-Wahhab", meaning: "The Bestower" },
  { id: 17, arabic: "ٱلرَّزَّاقُ", transliteration: "Ar-Razzaq", meaning: "The Provider" },
  { id: 18, arabic: "ٱلْفَتَّاحُ", transliteration: "Al-Fattah", meaning: "The Opener" },
  { id: 19, arabic: "ٱلْعَلِيمُ", transliteration: "Al-Alim", meaning: "The All-Knowing" },
  { id: 20, arabic: "ٱلْقَابِضُ", transliteration: "Al-Qabid", meaning: "The Withholder" },
  { id: 21, arabic: "ٱلْبَاسِطُ", transliteration: "Al-Basit", meaning: "The Expander" },
  { id: 22, arabic: "ٱلْخَافِضُ", transliteration: "Al-Khafid", meaning: "The Reducer" },
  { id: 23, arabic: "ٱلرَّافِعُ", transliteration: "Ar-Rafi", meaning: "The Exalter" },
  { id: 24, arabic: "ٱلْمُعِزُّ", transliteration: "Al-Mu'izz", meaning: "The Giver of Honor" },
  { id: 25, arabic: "ٱلْمُذِلُّ", transliteration: "Al-Mudhill", meaning: "The Giver of Humility" },
  { id: 26, arabic: "ٱلسَّمِيعُ", transliteration: "As-Sami", meaning: "The All-Hearing" },
  { id: 27, arabic: "ٱلْبَصِيرُ", transliteration: "Al-Basir", meaning: "The All-Seeing" },
  { id: 28, arabic: "ٱلْحَكَمُ", transliteration: "Al-Hakam", meaning: "The Judge" },
  { id: 29, arabic: "ٱلْعَدْلُ", transliteration: "Al-Adl", meaning: "The Utterly Just" },
  { id: 30, arabic: "ٱللَّطِيفُ", transliteration: "Al-Latif", meaning: "The Subtle and Kind" },
  { id: 31, arabic: "ٱلْخَبِيرُ", transliteration: "Al-Khabir", meaning: "The All-Aware" },
  { id: 32, arabic: "ٱلْحَلِيمُ", transliteration: "Al-Halim", meaning: "The Forbearing" },
  { id: 33, arabic: "ٱلْعَظِيمُ", transliteration: "Al-Azim", meaning: "The Magnificent" },
  { id: 34, arabic: "ٱلْغَفُورُ", transliteration: "Al-Ghafur", meaning: "The Great Forgiver" },
  { id: 35, arabic: "ٱلشَّكُورُ", transliteration: "Ash-Shakur", meaning: "The Appreciative" },
  { id: 36, arabic: "ٱلْعَلِيُّ", transliteration: "Al-Ali", meaning: "The Most High" },
  { id: 37, arabic: "ٱلْكَبِيرُ", transliteration: "Al-Kabir", meaning: "The Most Great" },
  { id: 38, arabic: "ٱلْحَفِيظُ", transliteration: "Al-Hafiz", meaning: "The Preserver" },
  { id: 39, arabic: "ٱلْمُقِيتُ", transliteration: "Al-Muqit", meaning: "The Sustainer" },
  { id: 40, arabic: "ٱلْحَسِيبُ", transliteration: "Al-Hasib", meaning: "The Reckoner" },
  { id: 41, arabic: "ٱلْجَلِيلُ", transliteration: "Al-Jalil", meaning: "The Majestic" },
  { id: 42, arabic: "ٱلْكَرِيمُ", transliteration: "Al-Karim", meaning: "The Generous" },
  { id: 43, arabic: "ٱلرَّقِيبُ", transliteration: "Ar-Raqib", meaning: "The Watchful" },
  { id: 44, arabic: "ٱلْمُجِيبُ", transliteration: "Al-Mujib", meaning: "The Responsive" },
  { id: 45, arabic: "ٱلْوَاسِعُ", transliteration: "Al-Wasi", meaning: "The All-Encompassing" },
  { id: 46, arabic: "ٱلْحَكِيمُ", transliteration: "Al-Hakim", meaning: "The Wise" },
  { id: 47, arabic: "ٱلْوَدُودُ", transliteration: "Al-Wadud", meaning: "The Loving" },
  { id: 48, arabic: "ٱلْمَجِيدُ", transliteration: "Al-Majid", meaning: "The Glorious" },
  { id: 49, arabic: "ٱلْبَاعِثُ", transliteration: "Al-Ba'ith", meaning: "The Resurrector" },
  { id: 50, arabic: "ٱلشَّهِيدُ", transliteration: "Ash-Shahid", meaning: "The Witness" },
  { id: 51, arabic: "ٱلْحَقُ", transliteration: "Al-Haqq", meaning: "The Truth" },
  { id: 52, arabic: "ٱلْوَكِيلُ", transliteration: "Al-Wakil", meaning: "The Trustee" },
  { id: 53, arabic: "ٱلْقَوِيُّ", transliteration: "Al-Qawiyy", meaning: "The Strong" },
  { id: 54, arabic: "ٱلْمَتِينُ", transliteration: "Al-Matin", meaning: "The Firm" },
  { id: 55, arabic: "ٱلْوَلِيُّ", transliteration: "Al-Waliyy", meaning: "The Protecting Friend" },
  { id: 56, arabic: "ٱلْحَمِيدُ", transliteration: "Al-Hamid", meaning: "The Praiseworthy" },
  { id: 57, arabic: "ٱلْمُحْصِي", transliteration: "Al-Muhsi", meaning: "The Accounter" },
  { id: 58, arabic: "ٱلْمُبْدِئُ", transliteration: "Al-Mubdi", meaning: "The Originator" },
  { id: 59, arabic: "ٱلْمُعِيدُ", transliteration: "Al-Mu'id", meaning: "The Restorer" },
  { id: 60, arabic: "ٱلْمُحْيِي", transliteration: "Al-Muhyi", meaning: "The Giver of Life" },
  { id: 61, arabic: "ٱلْمُمِيتُ", transliteration: "Al-Mumit", meaning: "The Bringer of Death" },
  { id: 62, arabic: "ٱلْحَيُّ", transliteration: "Al-Hayy", meaning: "The Ever-Living" },
  { id: 63, arabic: "ٱلْقَيُّومُ", transliteration: "Al-Qayyum", meaning: "The Sustainer of All" },
  { id: 64, arabic: "ٱلْوَاجِدُ", transliteration: "Al-Wajid", meaning: "The Finder" },
  { id: 65, arabic: "ٱلْمَاجِدُ", transliteration: "Al-Maajid", meaning: "The Noble" },
  { id: 66, arabic: "ٱلْوَاحِدُ", transliteration: "Al-Wahid", meaning: "The One" },
  { id: 67, arabic: "ٱلْأَحَدُ", transliteration: "Al-Ahad", meaning: "The Unique One" },
  { id: 68, arabic: "ٱلصَّمَدُ", transliteration: "As-Samad", meaning: "The Eternal Refuge" },
  { id: 69, arabic: "ٱلْقَادِرُ", transliteration: "Al-Qadir", meaning: "The Able" },
  { id: 70, arabic: "ٱلْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meaning: "The Powerful" },
  { id: 71, arabic: "ٱلْمُقَدِّمُ", transliteration: "Al-Muqaddim", meaning: "The Expediter" },
  { id: 72, arabic: "ٱلْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meaning: "The Delayer" },
  { id: 73, arabic: "ٱلأَوَّلُ", transliteration: "Al-Awwal", meaning: "The First" },
  { id: 74, arabic: "ٱلْآخِرُ", transliteration: "Al-Akhir", meaning: "The Last" },
  { id: 75, arabic: "ٱلظَّاهِرُ", transliteration: "Az-Zahir", meaning: "The Manifest" },
  { id: 76, arabic: "ٱلْبَاطِنُ", transliteration: "Al-Batin", meaning: "The Hidden" },
  { id: 77, arabic: "ٱلْوَالِي", transliteration: "Al-Wali", meaning: "The Governor" },
  { id: 78, arabic: "ٱلْمُتَعَالِي", transliteration: "Al-Muta'ali", meaning: "The Supremely Exalted" },
  { id: 79, arabic: "ٱلْبَرُّ", transliteration: "Al-Barr", meaning: "The Source of Goodness" },
  { id: 80, arabic: "ٱلتَّوَّابُ", transliteration: "At-Tawwab", meaning: "The Accepter of Repentance" },
  { id: 81, arabic: "ٱلْمُنْتَقِمُ", transliteration: "Al-Muntaqim", meaning: "The Avenger" },
  { id: 82, arabic: "ٱلْعَفُوُّ", transliteration: "Al-Afuww", meaning: "The Pardoner" },
  { id: 83, arabic: "ٱلرَّؤُوفُ", transliteration: "Ar-Ra'uf", meaning: "The Most Kind" },
  { id: 84, arabic: "مَالِكُ ٱلْمُلْكُ", transliteration: "Malik al-Mulk", meaning: "Master of the Kingdom" },
  { id: 85, arabic: "ذُو ٱلْجَلَالِ وَٱلْإِكْرَامُ", transliteration: "Dhul-Jalali wal-Ikram", meaning: "Lord of Majesty and Honor" },
  { id: 86, arabic: "ٱلْمُقْسِطُ", transliteration: "Al-Muqsit", meaning: "The Equitable" },
  { id: 87, arabic: "ٱلْجَامِعُ", transliteration: "Al-Jami", meaning: "The Gatherer" },
  { id: 88, arabic: "ٱلْغَنِيُّ", transliteration: "Al-Ghani", meaning: "The Self-Sufficient" },
  { id: 89, arabic: "ٱلْمُغْنِيُّ", transliteration: "Al-Mughni", meaning: "The Enricher" },
  { id: 90, arabic: "ٱلْمَانِعُ", transliteration: "Al-Mani", meaning: "The Preventer" },
  { id: 91, arabic: "ٱلضَّارُ", transliteration: "Ad-Darr", meaning: "The Distresser" },
  { id: 92, arabic: "ٱلنَّافِعُ", transliteration: "An-Nafi", meaning: "The Benefactor" },
  { id: 93, arabic: "ٱلنُّورُ", transliteration: "An-Nur", meaning: "The Light" },
  { id: 94, arabic: "ٱلْهَادِي", transliteration: "Al-Hadi", meaning: "The Guide" },
  { id: 95, arabic: "ٱلْبَدِيعُ", transliteration: "Al-Badi", meaning: "The Incomparable Originator" },
  { id: 96, arabic: "ٱلْبَاقِي", transliteration: "Al-Baqi", meaning: "The Everlasting" },
  { id: 97, arabic: "ٱلْوَارِثُ", transliteration: "Al-Warith", meaning: "The Inheritor" },
  { id: 98, arabic: "ٱلرَّشِيدُ", transliteration: "Ar-Rashid", meaning: "The Guide to the Right Path" },
  { id: 99, arabic: "ٱلصَّبُورُ", transliteration: "As-Sabur", meaning: "The Patient" },
];
